rounding_large = 0
rounding_small = 0
font_family = JetBrains Mono Nerd Font
font_size = 12
font_family_monospace = JetBrains Mono Nerd Font
background = 0xff161616
base = 0xff080808
text = 0xffffffff
alternate_base = 0xff323232
accent = 0xffffffff
accent_secondary = 0xffaaaaaa
bright_text = 0xff161616
